### ISSUE TITLE
Scroll to top is missing media query

### ISSUE THREAD

**Issue by jwillmer** [serenader2014/decent#4]
If the screen gets to narrow the scroll to top button hides the text.
![image](https://cloud.githubusercontent.com/assets/1503577/15454175/b980615e-2030-11e6-8590-69eb26798846.png)

**Comment by serenader2014** [comment]
I will improve this part in next release.

**Comment by jwillmer** [comment]
This screenshot was made with 770px width, please reopen the issue.

![image](https://cloud.githubusercontent.com/assets/1503577/15495152/aceb5d18-218e-11e6-9763-385d634620e5.png)

**Comment by serenader2014** [comment]
As long as there is a floating button, it will always hiding the text behind it when the screen get narrow. And that's why I added the opacity to the button, and even more transparent when user stop scrolling after 2 seconds. I can't find any better solution. If you have a better idea, just tell me, and I will have a try.

**Comment by jwillmer** [comment]
What about removing the button earlier? Not with media query 500 but with 900?

**Comment by serenader2014** [comment]
I've improve the style in v1.1.3. Now the button will hidden when screen is smaller than 500px.
